
Khai báo các thư viện
```{r}
library("tidyverse")
library("ggplot2")
library("dplyr")
```

đọc dữ liệu vào biến
```{r}
setwd("D:/data/")
stockx <- read.csv(file="stockx.csv", header=TRUE)
stockx
```

lấy dữ liệu trong năm 2023
```{r}
# Lấy dữ liệu trong năm 2023
data_in_2023 <- stockx[stockx$release_year == 2023, ]
data_in_2023
```

Tạo bẳng thống kê số lượng bán được theo mặt hàng trong năm 2023
```{r}
data_sale_num <- data_in_2023 %>%
  group_by(shoes_name) %>%
  summarise(total_sale = sum(number_of_sales))
data_sale_num
```

Tạo bảng thống kê trung bình giá bán thấp nhất của từng mặt hàng trong năm 2023
```{r}
data_min_trade <- tapply(data_in_2023$min_all_trade_range, data_in_2023$shoes_name, mean)
data_min_trade <- data.frame(shoes_name = names(data_min_trade), min_trade = data_min_trade)
data_min_trade
```

Tạo bảng thống kê trung bình giá bán cao nhất của từng mặt hàng trong năm 2023
```{r}
data_max_trade <- tapply(data_in_2023$max_all_trade_range, data_in_2023$shoes_name, mean)
data_max_trade <- data.frame(shoes_name = names(data_max_trade), max_trade = data_max_trade)
data_max_trade
```

Gộp 3 bảng với nhau
```{r}
data_sale_num <- left_join(data_sale_num, data_min_trade, by = "shoes_name")
data_sale_num <- left_join(data_sale_num, data_max_trade, by = "shoes_name")
data_sale_num
```

Kết quả top 10 mẫu giày được bán nhiều nhất trong 2023
```{r}
top_10_sale <- data_sale_num[order(data_sale_num$total_sale, decreasing = TRUE), ][1:10, ]
top_10_sale
```

Trực quan hóa bằng biểu đồ cột
```{r}
# Tạo dataframe long format để phù hợp với biểu đồ cột nhóm
top_10_long <- tidyr::gather(top_10_sale, key = "variable", value = "value", -shoes_name)

# Vẽ biểu đồ cột nhóm
ggplot(top_10_long, aes(x = shoes_name, y = value, fill = as.factor(variable))) +
  geom_col(position = "dodge", width = 0.7, color = "black") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 40, hjust = 1, size = 9),
        legend.position = c(0.85, 0.9),  # Đặt vị trí của ô chú thích
        legend.direction = "vertical",  # Đặt hướng của ô chú thích
        legend.box = "horizontal",  # Đặt hộp ô chú thích
        legend.margin = margin(t = 0, b = 0, unit = "cm"),
        plot.title = element_text(hjust = 0.5)) +
  labs(x = "Tên giày", y = "Số lượng", title = "Top 10 Giày Bán Chạy Nhất Trong Năm 2023") +
  scale_fill_manual(values = c("total_sale" = "skyblue", "min_trade" = "lightgreen", "max_trade" = "lightcoral")) +
  guides(fill = guide_legend(title = "Chú thích"))
```

```{r}
# Đọc dữ liệu từ file CSV
library("gridExtra")
library("ggplot2")
stockx <- read.csv("D:/data/stockx.csv")

# Tạo bảng tần suất cho biểu đồ pie
brand <- sort(table(stockx$brand), TRUE)
brand

# Tạo bảng chéo cho biểu đồ line
brand_year <- table(stockx$release_year, stockx$brand)
brand_year
top_4_brand <- brand_year[, c('Adidas', 'Nike', 'New Balance', 'Reebok')]
top_4_brand

# Tính tổng của các hãng khác
other_year <- c(rowSums(brand_year[, !(colnames(brand_year) %in% c('Adidas', 'Nike', 'New Balance', 'Reebok'))]))
other_year


# Ghép mảng
top_4_year <- c(top_4_brand[,'Adidas'],top_4_brand[,'Nike'],top_4_brand[,'New Balance'],top_4_brand[,'Reebok'])
top_4_year
all_year <- c(top_4_year, other_year)
all_year

# Tạo dữ liệu cho biểu đồ pie
pie_data <- c(brand[0], brand[1], brand[2], brand[3], brand[4], sum(brand[5:length(brand)]))
pie_data

#pie(pie_data,labels = c(names(brand)[1:4], "Others"),
#    col = c('#3498DB', '#4169E1', '#6495ED', '#00BFFF', '#87CEEB'))
#pie(all_year, col = c('#FF4500','#FF8C00','#FFA07A','#FFD700','#FFE4B5'), labels = '')
#grid.circle(gp = gpar(fill = 'white'), r = 0.35)



# Tạo dataframe cho biểu đồ doughnut
doughnut_data <- data.frame(
  Category = c('Adidas', 'Nike', 'New Balance', 'Reebok', 'Others') ,
  Value = pie_data
)
year_data <- data.frame(
  Category = c('2019','2020','2021','2022','2023',
               '2019','2020','2021','2022','2023',
               '2019','2020','2021','2022','2023',
               '2019','2020','2021','2022','2023',
               '2019','2020','2021','2022','2023'),
  Value = all_year
)
# Vẽ biểu đồ doughnut

pie_chart <- ggplot(doughnut_data, aes(x = "", y = Value, fill = Category)) +
  geom_bar(stat = "identity", width = 2) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste(Category)), 
            position = position_stack(vjust = 0.5)) +
  theme_void()

donut_chart <- pie_chart + 
  geom_bar(data = year_data, aes(x = "", y = Value), stat = "identity", 
           width = 0.1, fill = 'white') +
  coord_polar(theta = "y") +
  geom_text(data = year_data, aes(label = paste(Category)), 
            position = position_stack(vjust = 0.5), color = "black") +
  theme_void()

grid.arrange(donut_chart)
```


```{r}

# Load webr
install.packages("webr")
update.packages(pkgs="htmltools", ask=FALSE)
library(webr)
```



